### ISSUE TITLE
raspike_etrobo.pyがSPIKE App3で使えない

### ISSUE THREAD

**Issue by IKDnot** [ETrobocon/RasPike#12]
2023/4/11 確認時点では「SPIKE App3」(LEGO® Education SPIKE™ App v. 3.x.x以降)でSPIKE OSの更新を行うとMuEditorで転送したraspike_etrobo.pyが実行できないようです。従来の「SPIKE App2」を使ってOSを更新することで実行可能となりますが、一度SPIKE App3でOS更新を実施した場合はSPIKE本体をダウングレードする必要があります。ダウングレードには若干の特殊な[手続き](https://afrel.co.jp/product/spike/technology-spike/basic/software-basic/54122/)が発生します。

つきまして、一時対応としてWikiの更新対応、あるいは恒久策としてSPIKE App3への対応をお願いします。

Wiki更新に関して
* Wiki内のPC向けセットアップ手順(win10/macOS)でSPIKEアプリをインストールする手順が記載されていますが、記載のURLですと、最新版のSPIKEアプリ(= 3.x.x台)ダウンロードサイトにジャンプします。
  * 代わりに、従来のSPIKE App2が使えるSPIKE Legacyのダウンロードサイトにジャンプするように案内いただきたいです。
  * legacyアプリダウンロードサイトURL: https://education.lego.com/en-us/downloads/spike-legacy-app/software
* もし、SPIKE App3でSPIKE OSの更新をしてしまった場合向けにダウングレード手順の記載があると親切かと思います。
  *  手順に関するURL: https://afrel.co.jp/product/spike/technology-spike/basic/software-basic/54122/

参考情報
 * [SPIKEアプリ2とSPIKEアプリ3の主な変更点](https://afrel.co.jp/product/spike/technology-spike/basic/software-basic/53557/)

**Comment by ytoi** [comment]
修正します

**Comment by ytoi** [comment]
wikiへの記述を行いました。遅くなりすいません。
