### ISSUE TITLE
RasPike-ART: 書き込み環境の構築中にJava環境のエラーで失敗する

### ISSUE THREAD

**Issue by kuboaki** [ETrobocon/RasPike#23]
RasPike-ARTブランチで
「書き込み環境のセットアップ」を実行中にJava Runtimeのエラーになって、処理が中断される。
（まぁ、Javaの実行環境は色々あるから）

>  make -f ../common/Makefile.raspike-art setup_spike_env                                                    
> (cd ../../RasPike-ART/spike;./spike_env_setup_linux.sh)
> Requirement already satisfied: pyusb in /Users/kuboaki/Documents/spike-rt/RasPike/RasPike-ART/tools/python/lib/python3.12/site-packages (1.2.1)
> The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
> Please visit http://www.java.com for information on installing Java.
> 
> mv: cannot move '/tmp/serial_temp_rule' to '/etc/udev/rules.d/99-serial.rules': No such file or directory
> sudo: udevadm: command not found
> make: *** [../common/Makefile.raspike-art:28: setup_spike_env] Error 1

**Comment by ytoi** [comment]
これはRasPikeが動作するRasPi上で実行されていますか？

**Comment by kuboaki** [comment]
あれ？これは、転送前にPC/Mac側で実施する作業と認識していますが。

**Comment by ytoi** [comment]
いえ、

ファイルの取得以降の操作はRasPi上での操作です。全てRasPi上で完結するようにできています。

**Comment by kuboaki** [comment]
あーそうなんですね、間違えました。つまりSPIKEにとってはラズパイがホストなんですね。で、PCはなくてもいいと。

**Comment by kuboaki** [comment]
そのくらいのことすら分かんらないんですねー。いかんなぁ。
はなからPCで作って転送するって思い込んでいる先入観がじゃましました。

**Comment by ytoi** [comment]
RadPiで動かして動いたら本件クローズお願いします

**Comment by kuboaki** [comment]
動きましたー。お騒がせしましたー。
そして、ARTの動作確認できるようになりました（が、組立ててあるのがETロボコン走行体じゃないんですー）。
